name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Node.js (necessary for Firebase CLI)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Clear npm cache (optional troubleshooting step)
      - name: Clear npm cache
        run: npm cache clean --force

      # Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Verify Firebase CLI installation
      - name: Verify Firebase CLI
        run: firebase --version

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
